// <auto-generated />
using System;
using ContasApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContasApplication.Migrations
{
    [DbContext(typeof(BankContext))]
    [Migration("20250528125604_teste")]
    partial class teste
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContasApplication.Models.DespesaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DespesaFixa")
                        .HasColumnType("boolean");

                    b.Property<int>("Etiqueta")
                        .HasColumnType("integer");

                    b.Property<int>("IdParcelado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MesFimParcelado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MesReferenciaId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeDespesa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Parcelado")
                        .HasColumnType("boolean");

                    b.Property<int>("QuantidadeParcelas")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeParcelasPagas")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<double>("ValorDespesa")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MesReferenciaId");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("ContasApplication.Models.Etiquetas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EtiquetaId")
                        .HasColumnType("integer");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Etiquetas");
                });

            modelBuilder.Entity("ContasApplication.Models.Mes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("MesReferencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeMes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("valorTotal")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Mes");
                });

            modelBuilder.Entity("ContasApplication.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int?>("Page")
                        .HasColumnType("integer");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ContasApplication.Models.DespesaModel", b =>
                {
                    b.HasOne("ContasApplication.Models.Mes", "MesReferencia")
                        .WithMany()
                        .HasForeignKey("MesReferenciaId");

                    b.Navigation("MesReferencia");
                });
#pragma warning restore 612, 618
        }
    }
}
